### ISSUE TITLE
Aesthetic issue when announcing to player when they've crossed over the border

### ISSUE THREAD

**Issue by utoc** [TehNut-Mods/ElsewhereBorder#1]
Hey TehNut,  The mod works great as server side only; the client was bungied back even when teleporting without any glitches I noticed.  The only issue is that the UUID gets announced directly after the message. [See here](http://i.imgur.com/B76yyCb.png)

**Comment by TehNut** [comment]
Update to 1.0.0-2. I fixed that at b77094fdea7e58796dcefde910f4dc9537b786a2
