### ISSUE TITLE
Crash when entering unbound dimensions 

### ISSUE THREAD

**Issue by utoc** [TehNut-Mods/ElsewhereBorder#3]
ElsewhereBorder config only has borders defined on 0 and -1, no other dimensions. (Erebus is dimension 66 for reference)

http://pastebin.com/K580RMji

The world is unplayable from that crash forward until you remove the ElsewhereBorder mod.

I don't have an updated client list as I am still in beta for a big release.  ElsewhereBorder 0.4 and Erebus 0.2a with FML 1448.  Let me know if I can be of any assistance.

**Comment by TehNut** [comment]
Does it crash in any other modded dimensions?

**Comment by utoc** [comment]
I actually got TWO crash reports, simultaniously when entering the twilight forest

http://pastebin.com/Nx6036xz and http://pastebin.com/jrMCqe0Q

Both of these are when running SSP only, no server involved

**Comment by TehNut** [comment]
Both of these have to do with a change to how bounds are stored per dimension. 

@tterrag1098 Thoughts?

**Comment by TehNut** [comment]
From a bit more looking, it seems to crash when you enter a dimension without a bounds set.

Can you try setting a bounds on one of those dimensions and seeing if it still crashes? Just to confirm my suspicions.

**Comment by TehNut** [comment]
Actually, should be fixed by 55c3bc5. Can you try the new build when it finishes?

**Comment by utoc** [comment]
Success!  Thanks tterrag and TehNut.
